import type { WorkspaceModuleDefinition, WorkspaceModuleId, WorkspaceZoneId } from '../types/weather'

export const WORKSPACE_ZONES: { id: WorkspaceZoneId; label: string }[] = [
  { id: 'leftRail', label: 'Left rail' },
  { id: 'rightRail', label: 'Right rail' },
  { id: 'bottomDock', label: 'Bottom dock' },
  { id: 'mapOverlay', label: 'Map overlay' },
  { id: 'focusPanel', label: 'Focus panel' },
]

export const WORKSPACE_MODULES: WorkspaceModuleDefinition[] = [
  {
    id: 'alerts',
    title: 'NWS Alerts',
    description: 'Active National Weather Service alerts with severity filters, map selection, and zoom actions.',
    category: 'alerts',
    defaultZone: 'leftRail',
    defaultSize: 'standard',
    defaultVisible: true,
    requiresMap: true,
    isLive: true,
  },
  {
    id: 'liveContext',
    title: 'Live Context',
    description: 'Curated outbound weather operations links for cameras, spotters, chasers, news, and scanners.',
    category: 'operations',
    defaultZone: 'rightRail',
    defaultSize: 'standard',
    defaultVisible: true,
    isExternalLinkOnly: true,
  },
  {
    id: 'spc',
    title: 'SPC Severe Context',
    description: 'Storm Prediction Center reports and Day 1 outlook context rendered from public SPC products.',
    category: 'convective',
    defaultZone: 'bottomDock',
    defaultSize: 'standard',
    defaultVisible: true,
    requiresMap: true,
    isLive: true,
  },
  {
    id: 'radar',
    title: 'Radar Playback',
    description: 'RainViewer public radar metadata with playback, frame selection, and opacity controls.',
    category: 'radar',
    defaultZone: 'bottomDock',
    defaultSize: 'standard',
    defaultVisible: true,
    requiresMap: true,
    isLive: true,
  },
  {
    id: 'cameras',
    title: 'Weather Cameras',
    description: 'Future module for vetted weather camera collections. No camera feeds are embedded in this build.',
    category: 'media',
    defaultZone: 'rightRail',
    defaultSize: 'compact',
    defaultVisible: false,
    isExternalLinkOnly: true,
    isPlaceholder: true,
  },
  {
    id: 'scanners',
    title: 'Scanner Links',
    description: 'Future module for scanner shortcuts. No live audio is embedded in this build.',
    category: 'media',
    defaultZone: 'rightRail',
    defaultSize: 'compact',
    defaultVisible: false,
    isExternalLinkOnly: true,
    isPlaceholder: true,
  },
  {
    id: 'weatherNews',
    title: 'Weather News',
    description: 'Curated official weather news, forecast discussions, and outlook product links for operator context.',
    category: 'reference',
    defaultZone: 'focusPanel',
    defaultSize: 'compact',
    defaultVisible: false,
    isExternalLinkOnly: true,
  },
  {
    id: 'sourceHealth',
    title: 'Source Health',
    description: 'Live status for the currently wired NWS, SPC, and RainViewer data sources.',
    category: 'status',
    defaultZone: 'mapOverlay',
    defaultSize: 'compact',
    defaultVisible: true,
  },
  {
    id: 'legendTime',
    title: 'Legend & Time',
    description: 'Placeholder for map legend, valid times, and layer attribution. Current controls remain in layer panels.',
    category: 'reference',
    defaultZone: 'mapOverlay',
    defaultSize: 'compact',
    defaultVisible: true,
    requiresMap: true,
    isPlaceholder: true,
  },
]

export const WORKSPACE_MODULE_BY_ID = new Map<WorkspaceModuleId, WorkspaceModuleDefinition>(
  WORKSPACE_MODULES.map((module) => [module.id, module]),
)
