/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 4acd255d83979d25a6219cad6e3b81e6)
interface __BaseEnv_Env {
	CONTROL_BUCKET: R2Bucket;
	ALLOWED_ORIGIN: "https://radar.wall.cloud";
	CONTROL_OBJECT_KEY: "control/polling.json";
	FOCUS_CONTROL_OBJECT_KEY: "control/focus.json";
	ADMIN_SERVICE_URL: "https://wallcloud-radar-admin-o76krwi72a-ue.a.run.app";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_ORIGIN" | "CONTROL_OBJECT_KEY" | "FOCUS_CONTROL_OBJECT_KEY" | "ADMIN_SERVICE_URL">> {}
}
