name: Deploy application to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  actions: read
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    uses: ./.github/workflows/radar-refresh.yml
